#
# This file was automatically generated by ReFrame based on 'reframe/settings.py'.  # noqa: E501
#
import os

prefix = os.getenv('WORKSPACE')
if prefix == '' or prefix is None:
    prefix = os.getenv('HOME')
reframe_workdir = '{}/ReFrame'.format(prefix)

site_configuration = {
    'systems': [
        {
            'name': 'generic',
            'descr': 'Generic example system',
            'hostnames': [
                'localhost'
            ],
            'partitions': [
                {
                    'name': 'login',
                    'scheduler': 'local',
                    'modules': [],
                    'access': [],
                    'environs': [
                        'builtin-gcc'
                    ],
                    'descr': 'Login nodes',
                    'launcher': 'local'
                }
            ]
        },
        {
            'name': 'submit01',
            'descr': 'submit01 login node',
            'hostnames': [
                'submit01'
            ],
            'modules_system': 'lmod',
            'stagedir': '{}/stage/'.format(reframe_workdir),
            'outputdir': '{}/output/'.format(reframe_workdir),
            'resourcesdir': '{}/resources'.format(reframe_workdir),
            'partitions': [
                {
                    'name': 'login',
                    'scheduler': 'local',
                    'modules': [],
                    'access': ['submit01'],
                    'environs': [
                        'foss',
                        'builtin-gcc',
                    ],
                    'descr': 'Login nodes',
                    'launcher': 'ssh'
                }
            ]
        },
        {
            'name': 'ubelix',
            'descr': 'UniBE HPC system UBELiX',
            'hostnames': [
                'submit'
            ],
            'modules_system': 'lmod',
            'stagedir': '{}/stage/'.format(reframe_workdir),
            'outputdir': '{}/output/'.format(reframe_workdir),
            'resourcesdir': '{}/resources'.format(reframe_workdir),
            'partitions': [
                {
                    'name': 'login',
                    'scheduler': 'local',
                    'modules': [],
                    'access': [],
                    'environs': [
                        'builtin-gcc'
                    ],
                    'descr': 'Login nodes',
                    'launcher': 'ssh'
                },
                {
                     'name': 'submit01',
                     'scheduler': 'local',
                     'modules': [],
                     'access': ['submit01'],
                     'environs': [
                       'foss',
                       'intel',
                       'builtin-gcc'
                     ],
                     'descr': 'Login node submit01',
                     'launcher': 'ssh'
                },
                {
                     'name': 'submit03',
                     'scheduler': 'local',
                     'modules': [],
                     'access': ['submit03'],
                     'environs': [
                       'foss',
                       'intel',
                       'builtin-gcc'
                     ],
                     'descr': 'Login node submit03',
                     'launcher': 'ssh'
                 },
                {
                    'name': 'ivy',
                    'scheduler': 'slurm',
                    'modules': [],
                    'access': ['--constraint=ivy'],
                    'environs': [
                        'foss',
                        'intel',
                        'pgi'
                    ],
                    'descr': 'ivybridge compute nodes',
                    'launcher': 'srun'
                },
                {
                    'name': 'broadwell',
                    'scheduler': 'slurm',
                    'modules': [],
                    'access': ['--constraint=broadwell'],
                    'environs': [
                        'foss',
                        'intel',
                        'pgi'
                    ],
                    'descr': 'broadwell compute nodes',
                    'launcher': 'srun'
                },
                {
                    'name': 'amd',
                    'scheduler': 'slurm',
                    'modules': [],
                    'access': ['--partition=amd'],
                    'environs': [
                        'foss',
                        'intel',
                        'pgi'
                    ],
                    'descr': 'compute nodes',
                    'launcher': 'srun'
                },
                {
                    'name': 'gpu',
                    'scheduler': 'slurm',
                    'modules': [],
                    'access': [
                        '--partition=gpu',
                        '--gres=gpu:gtx1080ti:1'
                    ],
                    'environs': [
                        'foss',
                        'intel',
                        'pgi'
                    ],
                    'descr': 'gpu compute nodes',
                    'launcher': 'srun'
                }
            ]
        }
    ],
    'environments': [
        {
            'name': 'builtin-gcc',
            'cc': 'gcc',
            'cxx': 'g++',
            'ftn': 'gfortran'
        },
        {
            'name': 'foss',
            'modules': [
                'foss'
            ],
            'cc': 'mpicc',
            'cxx': 'mpic++',
            'ftn': 'mpifort'
        },
        {
            'name': 'intel',
            'modules': [
                'intel'
            ],
            'cc': 'mpiicc',
            'cxx': 'mpiicpc',
            'ftn': 'mpiifort'
        },
        {
            'name': 'pgi',
            'modules': [
                'PGI'
            ],
            'cc': 'pgcc',
            'cxx': 'pgc++',
            'ftn': 'pgf90'
        }
    ],
    'logging': [
        {
            'level': 'debug',
            'handlers': [
                {
                    'type': 'file',
                    'name': 'reframe.log',
                    'level': 'debug',
                    'format': '[%(asctime)s] %(levelname)s: %(check_info)s: %(message)s',  # noqa: E501
                    'append': False
                },
                {
                    'type': 'stream',
                    'name': 'stdout',
                    'level': 'info',
                    'format': '%(message)s'
                },
                {
                    'type': 'file',
                    'name': 'reframe.out',
                    'level': 'info',
                    'format': '%(message)s',
                    'append': False
                }
            ],
            'handlers_perflog': [
                {
                    'type': 'filelog',
                    'prefix': '%(check_system)s/%(check_partition)s',
                    'level': 'info',
                    'format': '%(asctime)s|reframe %(version)s|%(check_info)s|jobid=%(check_jobid)s|%(check_perf_var)s=%(check_perf_value)s|ref=%(check_perf_ref)s (l=%(check_perf_lower_thres)s, u=%(check_perf_upper_thres)s)|%(check_perf_unit)s',  # noqa: E501
                    'append': True,
                    'basedir': '{}/logs/'.format(reframe_workdir)
                }
            ],
#            'target_systems': [
#                'ubelix', 'submit01'
#            ]
        }
    ],
    'general': [
        {
            'check_search_path': [
                'checks/'
            ],
            'check_search_recursive': True
        }
    ]
}
